#!/bin/sh

# Start sxkhd deamon
pgrep -x sxhkd > /dev/null || sxhkd &

# Start picom compositor
picom --config $HOME/.config/picom/picom.conf &

# Load wallpaper and cached colorscheme
wal -i ~/Pictures/Wal/bg1.jpg &

# Launch polybar
$HOME/.config/polybar/launch.sh &

# Monitor and workspace config
bspc monitor -d 1 2 3 4 5

# source pywal-generated colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color11"

# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

bspc config border_width        1
bspc config window_gap          40

bspc config top_padding         20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
